title: Sindyoke's Android Homepage
author: Sanja Drakulović
description: Android Developer, trying to find a deeper meaning and make world a better place

show_downloads: false
google_analytics:
url: http://sindyoke.com
# category_dir: /
theme: jekyll-theme-slate
permalink: /:year/:month/:day/:title
# markdown: kramdown?
# highlighter: rouge?
